name: build
on: [push]
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          path: RoutesImportExport
      - name: Set version
        id: version
        run: echo "::set-output name=version::$(cat RoutesImportExport/env/VERSION)"
      - name: archive release
        uses: thedoctor0/zip-release@master
        with:
          filename: Routes-Import-Export_v${{ steps.version.outputs.version }}.zip
          exclusions: '*.git* /RoutesImportExport/env/* *.github* *.md *.zip /*node_modules/* .editorconfig'
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          body_path: RoutesImportExport/README.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload retail artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Routes-Import-Export_v${{ steps.version.outputs.version }}.zip
          asset_name: Routes-Import-Export_v${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip
